### ISSUE TITLE
Decrypt Associate Model

### ISSUE THREAD

**Issue by aouchachacha** [BrendonKoz/CakePHP-Mcrypt-Behavior#3]
Hi,

Thanks a lot for your Behavior! I want to submit you an idea :

In your Model A add this line : 
public $actsAs = array('Mcrypt' => array('fields' => array('ModelB.field1', 'ModelB.field2', 'ModelC.field1')));

And then, in your Behavior, in the _decryptArray() function, if the $key isn't found in $this->config[$this->modelName]['fields'], test if $curModel.'.'.$key is in_array.

Here is my code : 

if(in_array($key, $this->config[$this->modelName]['fields']) && $curModel == $this->modelName){
    $values[$key] = $this->_decryptField($value);
} else {
    if(in_array($curModel.'.'.$key, $this->config[$this->modelName]['fields'])){
        $values[$key] = $this->_decryptField($value);
    }
}

I think it works fine. That's the case on my website.

Happy coding!

PS : i'm using it on cakePhp 2.3 and it works fine.

**Comment by BrendonKoz** [comment]
Unfortunately I was extremely slow to respond here, and it appears your pull request (with the other suggestion / change) has been removed from my project repository. I've had some issues with this Behavior when using it with Containable, and in an attempt for a quick and easy fix implemented this change. Even more unfortunate: it did not help with my own problem. On the plus side, that means I'll be looking in to further extending this Behavior to get things working again - hopefully in a slightly more elegant manner, if possible.

I'll be updating my code so that it will now be compatible with (tested) CakePHP version 2.6.1.
